services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  anxiety:
    image: anxiety-api
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

  product-warning:
    image: product-warning-api
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"

  nina:
    image: nina-api
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8081"

  autobahn:
    image: autobahn-api
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8082"
