services:
  db:
    image: postgis/postgis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  risiko-radar:
    image: risiko-radar-api
    depends_on:
      - db
      - redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

  product-warning:
    image: product-warning-api
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8000"

  nina:
    image: nina-api
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8000"

  autobahn:
    image: autobahn-api
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8000"
