services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  anxiety:
    image: anxiety-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

  product-warning:
    image: product-warning-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"