openapi: '3.0.2'
info:
  title: Anxiety
  description: | 
    Collection of all security related APIs for Germany.
    Supplying the information to anxiety frontend.
  version: '0.1'
servers:
  - url: https://localhost:8000
    description: Local server

tags:
  - name: dashboard
    description: 'Retrieving information for the dashboard'
  - name: map
    description: "Retrieving information for the map of germany"
  - name: world-map
    description: "Retrieving information for the worldmap"

paths:
  /dashboard:
    get:
      tags:
        - dashboard
      description: 'Get all dashboard items.'
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/dashboardItem'
  /dashboard/{id}:
    get:
      tags:
        - dashboard
      description: 'Get a dashboard item by id.'
      parameters:
        - name: id
          in: path
          description: 'ID of the dashboard item to get.'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dashboardItemDetails'
        '404':
          description: Not Found
  /dashboard/update:
    get:
      tags:
        - dashboard
      description: ''
      parameters:
        - name: timestamp
          in: query
          description: 'Timestamp of the last update.'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /map:
    get:
      tags:
        - map
      description: 'Get all map items.'
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/mapItem'
  /map/{id}:
    get:
      tags:
        - map
      description: 'Get a map item by id.'
      parameters:
        - name: id
          in: path
          description: 'ID of the map item to get.'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mapItemDetails'
        '404':
          description: Not Found
  /map/update:
    get:
      tags:
        - map
      description: ''
      parameters:
        - name: timestamp
          in: query
          description: 'Timestamp of the last update.'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /world-map:
    get:
      tags:
        - world-map
      description: 'Get all country items.'
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/countryItem'
  /world-map/{id}:
    get:
      tags:
        - world-map
      description: 'Get a country item by id.'
      parameters:
        - name: id
          in: path
          description: 'ID of the country item to get.'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/countryItemDetails'
        '404':
          description: Not Found
  /world-map/update:
    get:
      tags:
        - world-map
      description: ''
      parameters:
        - name: timestamp
          in: query
          description: 'Timestamp of the last update.'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK

components:
  schemas:
    dashboardItem:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - interpol_red
            - interpol_un
            - food_warning
            - product_warning
            - travel_warning
            - country_representetive
        severity:
          type: string
          enum:
            - information
            - warning
            - danger
            - extreme danger
        title:
          type: string
        description:
          type: string
        since:
          type: integer
    dashboardItemDetails:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - Interpol_Red
            - Interpol_UN
            - Product_Warning
            # TODO: Add remaining "not map" types
        details:
          type: object
    mapItem:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - weather_flood
            - weather_storm
            - weather_disaster
            - street_closure
            - street_report
            - police
            - air_quality
            - radiation
        title:
          type: string
        position:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
        area:
          oneOf:
            - type: number
              description: 'Radius in meters.'
            - type: array
              description: 'Array for polygon.'
              items:
                type: number
    mapItemDetails:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - weather_flood
            - weather_storm
            - weather_disaster
            - street_closure
            - street_report
            - police
            - air_quality
            - radiation
        details:
          type: object
    countryItem:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - interpol_red
            - interpol_un
            - travel_warning
            - country_representetive
        country:
          type: string
    countryItemDetails:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - Interpol_Red
            - Interpol_UN
            - Travel_Warning
        details:
          type: object

