export interface IEmbassyModel {
  country: string | undefined;
  city: string | undefined;
  description: string | undefined;
  leader: string | undefined;
  address: string | undefined;
  open: string | undefined;
  contact: string | undefined;
  emergencyphone: string | undefined;
  phone: string | undefined;
  fax: string | undefined;
  website: string | undefined;
  mail: string | undefined;
  lastModified: number | undefined;
  postal: string | undefined;
  county: string | undefined;
  misc: string | undefined;
  remark: string | undefined;
}
